replicaCount: 1

image:
  repository: "pritiyadav537/harnesstest"
  tag: "1.0.0"
  pullPolicy: IfNotPresent

deployment:
  name: springboothelloworld
  port: 8080

service:
  name: springboothelloworld
  type: NodePort
  port: 8080
  nodePort: 31000
