replicaCount: 1

image:
  repository: "spring-boot-helloworld"
  tag: "v1"
  pullPolicy: IfNotPresent

deployment:
  name: spring-boot-helloworld
  port: 808

service:
  name: spring-boot-helloworld
  type: NodePort
  port: 8080
  nodePort: 31000
